name: caller

on:
  workflow_dispatch:
    branches:
      - main
  schedule: # schedule action every five minutes
      # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: remote
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: echo "hello from caller"

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          env: release
