name: remote

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - run: "::set-output name=version::$(cat .version)"
        id: set_version

      - run: echo "hello from ${{ steps.set_version.outputs.version}}"
