name: two

on:
  workflow_run:
    workflows: ["one"]
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - echo "action_state=yellow" >> $GITHUB_ENV
      - name: Set env
        run: echo "GITHUB_SHA=refs/pull/1/merge" >> $GITHUB_ENV
      - run: echo "two"
